version: '3.8'
services:
  mysql:
    build:
      context: mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes: 
      - type: volume
        source: mysql
        target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      MYSQL_ROOT_PASSWORD: test123
    networks:
      - mysql-network

networks:
 mysql-network:
    driver: bridge

volumes:
  mysql: